repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v1.2.0
  hooks:
    - id: debug-statements
    - id: check-json
    - id: check-merge-conflict
    - id: end-of-file-fixer
      files: \.(py|html)$
    - id: flake8
      args:
      - --max-line-length=120
    - id: trailing-whitespace
      files: \.([jt]sx?)$
