default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: daily_development
  url: postgres://postgres:postgres@localhost/daily

test:
  <<: *default
  database: daily_test
  url: postgres://postgres:postgres@localhost/daily

production:
  <<: *default
  database: daily_production
  username: daily
  password: <%= ENV["DAILY_DATABASE_PASSWORD"] %>
