require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Lint/MissingCopEnableDirective:
  Enabled: false

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
